name: strativa_frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  cached_network_image: ^3.4.1
  pinput: ^5.0.1
  mobile_scanner: ^6.0.7
  pretty_qr_code: ^3.4.0
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env.development

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/square_logo.png"